# https://github.com/docker/docker.github.io/blob/master/compose/compose-file/compose-versioning.md#version-37
# Make sure to use Docker Engine version 18.06.0 or higher.
version: "3.7"

services:

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: "no"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=login-db
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes